title: ss
description: >- # this means to ignore newlines until "baseurl:"
 Replication Package and Dataset for the paper: How likely is an inflation disaster?
baseurl: "/Test" # the subpath of your site, e.g. /blog
url: "https://s-mahdihosseini.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  s-mahdihosseini

# Build settings
# theme: jekyll-theme-cayman
theme: jekyll-theme-midnight
