title: Your Site Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a description of your site.
baseurl: "/Test" # the subpath of your site, e.g. /blog
url: "https://s-mahdihosseini.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  s-mahdihosseini

# Build settings
theme: minima # or any other theme you want to use
